version: '3'

networks:
  mongo_network:
    external: true

services:
  mongo:
    container_name: mongo
    image: mongo:4
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: changeme
    volumes:
      - ./data:/data/db
      - ./mongod.conf:/etc/mongod.conf
    networks:
      - mongo_network
