version: '3'

networks:
  mysql_network:
    external: true

services:
  mysql:
    container_name: mysql
    image: mysql:8
    user: "${UID}:${GID}"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./data/:/var/lib/mysql/
    networks:
      - mysql_network
