version: '3'

networks:
  socialdevelop-server-network:
    external: true

services:
  socialdevelop_server_nginx:
    image: nginx:alpine
    volumes:
      - ./images/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - phpfpm
    networks:
      - socialdevelop-server-network
  phpfpm:
    build: images/php
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html # /var/www/html/app/public для лумена например
    command: php-fpm
    environment:
      APP_ENV: local
      APP_DEBUG: 'true'
      APP_KEY: SomeRandomKey!!!
      APP_LOCALE: en
      APP_FALLBACK_LOCALE: en
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_DATABASE: lumen
      DB_USERNAME: lumen
      DB_PASSWORD: secret
      MEMCACHED_HOST: cache
      CACHE_DRIVER: memcached
    networks:
      - socialdevelop-server-network
  # db:
  #   image: mysql
  #   environment:
  #     MYSQL_ROOT_PASSWORD: secret
  #     MYSQL_DATABASE: lumen
  #     MYSQL_USER: lumen
  #     MYSQL_PASSWORD: secret
  cache:
    image: memcached
    networks:
      - socialdevelop-server-network
