version: '3'

networks:
  proxy_network:
    external: true

services:
  testparcel_client:
    image: newbie39/parcel
    user: "${UID}:${GID}"
    command: parcel --hmr-port 9000 src/index.html
    volumes:
      - .:/code
    networks:
      - proxy_network
