version: '3'

networks:
  proxy_network:
    external: true
  mysql_network:
    external: true

services:
  oreshek_server:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - oreshek_phpfpm
    networks:
      - default
      - proxy_network
  oreshek_phpfpm:
    image: newbie39/php_for_lumen:version1
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html/public
    command: php-fpm
    environment:
      APP_ENV: local
      APP_DEBUG: 'true'
      APP_KEY: SomeRandomKey!!!
      APP_LOCALE: en
      APP_FALLBACK_LOCALE: en
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_DATABASE: lumen
      DB_USERNAME: lumen
      DB_PASSWORD: secret
      MEMCACHED_HOST: cache
      CACHE_DRIVER: memcached
    networks:
      - default
      - mysql_network
  oreshek_cache:
    image: memcached
    networks:
      - default
