version: '3'

networks:
  proxy_network:
    external: true

services:
  oreshek_client:
    image: ebiven/vue-cli
    command: yarn serve
    volumes:
      - .:/code
    networks:
      - proxy_network
